#!/usr/bin/python

import time;
import random;
from colorama import *;

print("======================================");
print("Dajamajner");
print("======================================");

while (True):
  money = random.uniform(0, 1000);
  print(Fore.GREEN, end="\r");
  print("Money gived: ", money, "$", end="\r");
  time.sleep(0.1);
