#!/usr/bin/python

import random;
import time;

print("======================================");
print("Dajamajner");
print("======================================");
txt = input("enter currency: ");
print("Selected currency: ", txt);
time.sleep(1);

while (True):
	money = random.uniform(0, 1000);
	print("====================================");
	print("\033[32mGiven:", money, (txt)+"s", "\033[0m");
  
